### ISSUE TITLE
Continuous errors

### ISSUE THREAD

**Issue by mattmcnabb** [ironmansoftware/universal-automation#16]
#### Describe the Issue

In testing I began seeing errors and can't get rid of this condition now.

#### To Reproduce

```powershell
$Token = Start-UAServer -Port 10000 -GitRemote "https://github.com/mattmcnabb/UABeta.git" -GitRemoteCredential matt
Connect-UAServer -ComputerName "http://localhost:10000" -AppToken $Token
$Dashboard = New-UADashboard
Start-UDDashboard -Dashboard $Dashboard -Port 10001
```

now when I visit the dashboard I get a repeated error in the server console every couple seconds:

```
[00:33:55 ERR] Connection id "0HLRQ1MVHRMPA", Request id "0HLRQ1MVHRMPA:0000007F": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalAutomation.ScriptController.Get(Int64 id)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequests>d__188`1.MoveNext()
```

#### Expected behavior

It should just work - duh!

#### Screenshots

![image](https://user-images.githubusercontent.com/6998507/70298838-02b89680-17c1-11ea-831b-6a6629a8fbfc.png)

![image](https://user-images.githubusercontent.com/6998507/70298877-30054480-17c1-11ea-93c1-c79f6f3c931a.png)

#### Version Information

- **Host Operating System**: Windows 10
- **Host PowerShell Version**: Windows PowerShell 5.1
- **Universal Automation Version**: 1.0.0 build 2103
- **Universal Dashboard Version**: 2.7.0
- **UD Hosting Method**: PowerShell

**Comment by adamdriscoll** [comment]
Whoa! It's mad!

**Comment by adamdriscoll** [comment]
New build headed your way. This had something to do with tag lookups.

**Comment by mattmcnabb** [comment]
@adamdriscoll I'm still getting this error in the UA console and the related error in the dashboard even after downloading the 2189 build. Think I need to delete tags, or do I just need to start over with a fresh DB? Thanks!

![image](https://user-images.githubusercontent.com/6998507/70437936-bab4a080-1a5a-11ea-9d82-ae750fa061a7.png)
